version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:2024.11.1
      docker_layer_caching: true
    steps:
      - checkout
      - run: command: make deps
      - run: command: make test
      - run: command: make docker_push

workflows:
  version:
  basic:
    jobs:
      - build-and-test